DEBUG 2024-11-06 06:48:29.970 UTC: 	 CRAB Client version: v3.240930
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Running on: Linux lxplus929.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Not using Singularity
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-06 06:48:29.972 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-06 06:48:29.972 UTC: 	 Loading CRAB configuration file.
ERROR 2024-11-06 06:48:29.994 UTC: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab_conf.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-11-06 06:48:29.994 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 342, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py", line 16
    config.Data.inputDataset = '/Muon/Run2022C-27Jun2023-v1/AOD
                                                               ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 57, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 350, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py
Due to error:
EOL while scanning string literal (crab_conf.py, line 16)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 342, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py", line 16
    config.Data.inputDataset = '/Muon/Run2022C-27Jun2023-v1/AOD
                                                               ^
SyntaxError: EOL while scanning string literal


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 91, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab_conf.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-11-06 06:48:30.000 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-07 07:53:36.550 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Running on: Linux lxplus9107.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Not using Singularity
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Executing command: 'kill'
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-07 11:59:41.763 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Not using Singularity
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-07 11:59:41.766 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-07 11:59:41.766 UTC: 	 Loading CRAB configuration file.
ERROR 2024-11-07 11:59:41.809 UTC: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-11-07 11:59:41.809 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 96, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-11-07 11:59:41.816 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-07 13:24:13.914 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Not using Singularity
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Executing command: 'status'
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-07 13:24:13.918 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2022F is not a valid CRAB project directory.
ERROR 2024-11-07 13:24:13.918 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2022F is not a valid CRAB project directory.
INFO 2024-11-07 13:24:13.922 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-08 14:34:42.795 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Running on: Linux lxplus950.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Not using Singularity
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-08 14:34:42.796 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-08 14:34:42.838 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-08 14:34:42.838 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-08 14:34:43.013 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-08 14:34:43.017 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2022C' already exists 
Please change the requestName in the config file
ERROR 2024-11-08 14:34:43.017 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2022C' already exists 
Please change the requestName in the config file
INFO 2024-11-08 14:34:43.022 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 08:39:57.206 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Not using Singularity
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-09 08:39:57.207 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-09 08:39:57.207 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-09 08:39:57.236 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-09 08:39:57.236 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023C0' already exists 
Please change the requestName in the config file
ERROR 2024-11-09 08:39:57.236 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023C0' already exists 
Please change the requestName in the config file
INFO 2024-11-09 08:39:57.240 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 08:40:29.521 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 08:40:29.521 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Not using Singularity
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-09 08:40:29.524 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-09 08:40:29.524 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-09 08:40:29.575 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-09 08:40:29.575 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023B0' already exists 
Please change the requestName in the config file
ERROR 2024-11-09 08:40:29.575 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023B0' already exists 
Please change the requestName in the config file
INFO 2024-11-09 08:40:29.580 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 13:10:14.679 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Not using Singularity
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Executing command: 'status'
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-09 13:10:14.681 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
ERROR 2024-11-09 13:10:14.681 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
INFO 2024-11-09 13:10:14.685 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 13:10:18.471 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Not using Singularity
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Executing command: 'status'
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-09 13:10:18.472 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
ERROR 2024-11-09 13:10:18.472 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
INFO 2024-11-09 13:10:18.475 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-10 07:19:22.786 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Running on: Linux lxplus936.cern.ch 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 18 14:35:40 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Not using Singularity
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Executing command: 'status'
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-10 07:19:22.787 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023C1/ is not a valid CRAB project directory.
ERROR 2024-11-10 07:19:22.787 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023C1/ is not a valid CRAB project directory.
INFO 2024-11-10 07:19:22.789 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-12 03:15:59.815 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Running on: Linux lxplus962.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Not using Singularity
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Executing command: 'status'
DEBUG 2024-11-12 03:15:59.816 UTC: 	 Could not find CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3; creating a new one.
ERROR 2024-11-12 03:15:59.819 UTC: 	 Unhandled Exception!
ERROR 2024-11-12 03:15:59.819 UTC: 	 [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 268, in __init__
    self.crab3dic = self.getConfiDict()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 570, in getConfiDict
    with open(crabCacheFileName_tmp, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
ERROR 2024-11-12 03:15:59.820 UTC: 	 ERROR: PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
ERROR 2024-11-12 03:15:59.821 UTC: 	 
	Please email cmstalk+computing-tools@dovecotmta.cern.ch for support with the crab.log file or crab.log URL.
ERROR 2024-11-12 03:15:59.821 UTC: 	 	Client Version: v3.241030
ERROR 2024-11-12 03:15:59.821 UTC: 	 	Please use 'crab uploadlog' to upload the log file /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log to the CRAB cache.
DEBUG 2024-11-12 03:28:58.750 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Running on: Linux lxplus962.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Not using Singularity
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Executing command: 'status'
DEBUG 2024-11-12 03:28:58.752 UTC: 	 Could not find CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3; creating a new one.
ERROR 2024-11-12 03:28:58.755 UTC: 	 Unhandled Exception!
ERROR 2024-11-12 03:28:58.755 UTC: 	 [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 268, in __init__
    self.crab3dic = self.getConfiDict()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 570, in getConfiDict
    with open(crabCacheFileName_tmp, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
ERROR 2024-11-12 03:28:58.756 UTC: 	 ERROR: PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
ERROR 2024-11-12 03:28:58.756 UTC: 	 
	Please email cmstalk+computing-tools@dovecotmta.cern.ch for support with the crab.log file or crab.log URL.
ERROR 2024-11-12 03:28:58.757 UTC: 	 	Client Version: v3.241030
ERROR 2024-11-12 03:28:58.757 UTC: 	 	Please use 'crab uploadlog' to upload the log file /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log to the CRAB cache.
DEBUG 2024-11-12 04:17:12.021 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Running on: Linux lxplus9121.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Not using Singularity
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-17 07:07:32.003 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Executing command: 'status'
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-17 07:07:32.004 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023CC/ is not a valid CRAB project directory.
ERROR 2024-11-17 07:07:32.004 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023CC/ is not a valid CRAB project directory.
INFO 2024-11-17 07:07:32.006 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-17 07:14:38.995 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-17 07:27:10.208 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-17 07:27:10.209 UTC: 	 Will use CRAB configuration file crab_conf_file.py
DEBUG 2024-11-17 07:27:10.209 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-17 07:27:10.260 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-17 07:27:10.260 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2024-11-17 07:27:10.260 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 386, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 364, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2024-11-17 07:27:10.264 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-17 08:25:20.117 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Not using Singularity
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Executing command: 'getlog'
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-12-31 12:20:37.228 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-31 12:20:37.229 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-31 12:20:37.229 UTC: 	 Not using Singularity
DEBUG 2024-12-31 12:20:37.229 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-31 12:20:37.229 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-31 12:20:37.230 UTC: 	 Could not find CRAB cache file /u/user/wkwon/.crab3; creating a new one.
INFO 2024-12-31 12:20:37.234 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-12-31 12:20:37.235 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-31 12:20:37.242 UTC: 	 Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('skim').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT, RECOVER.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-31 12:20:37.242 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('skim').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT, RECOVER.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-31 12:20:37.245 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2024-12-31 12:21:47.620 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-31 12:21:47.621 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-31 12:21:47.621 UTC: 	 Not using Singularity
DEBUG 2024-12-31 12:21:47.621 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-31 12:21:47.621 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-31 12:21:47.622 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
INFO 2024-12-31 12:21:47.624 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-12-31 12:21:47.625 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-31 12:21:47.627 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-31 12:21:47.628 UTC: 	 Working area '/u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_Run2022C-27Jun2023-v1' already exists 
Please change the requestName in the config file
ERROR 2024-12-31 12:21:47.628 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_Run2022C-27Jun2023-v1' already exists 
Please change the requestName in the config file
INFO 2024-12-31 12:21:47.632 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2024-12-31 12:22:27.983 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-31 12:22:27.983 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-31 12:22:27.983 UTC: 	 Not using Singularity
DEBUG 2024-12-31 12:22:27.984 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-31 12:22:27.984 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-12-31 12:22:27.984 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
ERROR 2024-12-31 12:22:27.986 UTC: 	 Cannot find .requestcache file in CRAB project directory /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_Run2022C-27Jun2023-v1
ERROR 2024-12-31 12:22:27.987 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_Run2022C-27Jun2023-v1
INFO 2024-12-31 12:22:27.991 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2024-12-31 16:01:10.926 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-31 16:01:10.926 UTC: 	 Running on: Linux cms01.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-31 16:01:10.926 UTC: 	 Not using Singularity
DEBUG 2024-12-31 16:01:10.926 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-31 16:01:10.926 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-31 16:01:10.927 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
INFO 2024-12-31 16:01:10.929 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-12-31 16:01:10.930 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-31 16:01:10.936 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-31 16:01:10.936 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2024-12-31 16:01:10.936 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 386, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 364, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2024-12-31 16:01:10.941 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2025-01-02 05:38:13.442 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-02 05:38:13.442 UTC: 	 Running on: Linux cms.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-02 05:38:13.442 UTC: 	 Not using Singularity
DEBUG 2025-01-02 05:38:13.442 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-02 05:38:13.442 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-02 05:38:13.443 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
INFO 2025-01-02 05:38:13.444 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2025-01-02 05:38:13.444 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-02 05:38:13.448 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-02 05:38:13.448 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2025-01-02 05:38:13.448 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 386, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 364, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2025-01-02 05:38:13.450 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2025-01-02 06:26:31.978 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-02 06:26:31.978 UTC: 	 Running on: Linux cms.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-02 06:26:31.978 UTC: 	 Not using Singularity
DEBUG 2025-01-02 06:26:31.978 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-02 06:26:31.978 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-02 06:26:31.978 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
INFO 2025-01-02 06:26:31.980 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2025-01-02 06:26:31.980 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-02 06:26:31.983 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-02 06:26:31.984 UTC: 	 Working area '/u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_crab_Run2022C-27Jun2023-v1_2' already exists 
Please change the requestName in the config file
ERROR 2025-01-02 06:26:31.984 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab_projects/crab_crab_Run2022C-27Jun2023-v1_2' already exists 
Please change the requestName in the config file
INFO 2025-01-02 06:26:31.986 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2025-01-03 05:23:43.567 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-03 05:23:43.567 UTC: 	 Running on: Linux cms.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-03 05:23:43.567 UTC: 	 Not using Singularity
DEBUG 2025-01-03 05:23:43.567 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-03 05:23:43.567 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-03 05:23:43.567 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
INFO 2025-01-03 05:23:43.584 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2025-01-03 05:23:43.584 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-03 05:23:43.624 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-03 05:23:43.624 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2025-01-03 05:23:43.624 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 386, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 364, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2025-01-03 05:23:43.626 UTC: 	 Log file is /u/user/wkwon/work/CMSSW_14_0_19_patch2/src/work/skim/crab.log
DEBUG 2025-01-03 10:55:51.480 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-03 10:55:51.480 UTC: 	 Running on: Linux cms.knu.ac.kr 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-03 10:55:51.480 UTC: 	 Not using Singularity
DEBUG 2025-01-03 10:55:51.480 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-03 10:55:51.480 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-03 10:55:51.481 UTC: 	 Found CRAB cache file /u/user/wkwon/.crab3
